---
Name: shibboleth
After:
  - 'mysite'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Member:
  extensions:
    - ShibbolethSubject
SecurityAdmin:
  extensions:
    - ShibbolethSecurityAdminHelper
Member:
  unique_identifier_field: UniqueIdentifier